services:
  backend:
    build: .
    command: uvicorn backend_sync.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+pysqlite:///./data/backend.db
      - DATA_DIR=/app/data
      - JWT_SECRET=${JWT_SECRET:-change-me}

  worker:
    build: .
    command: python -m workers.service
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=sqlite+pysqlite:///./data/backend.db
      - DATA_DIR=/app/data
      - JWT_SECRET=${JWT_SECRET:-change-me}
    depends_on:
      - backend
    profiles: [worker]
